name: Build on ubuntu against pico-sdk develop
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clean workspace
        run: |
          echo "Cleaning up previous run"
          rm -rf "${{ github.workspace }}"
          mkdir -p "${{ github.workspace }}"

      - name: Checkout project
        uses: actions/checkout@v4
        with:
          path: pico-pulse

      - name: Checkout pico-sdk/develop
        uses: actions/checkout@v4
        with:
          repository: raspberrypi/pico-sdk
          ref: develop
          path: pico-sdk

      - name: Checkout pico-sdk submodules
        working-directory: ${{github.workspace}}/pico-sdk
        run: git submodule update --init

      - name: Install dependencies
        run: |
          sudo apt-get install cmake
          sudo apt-get install gcc-arm-none-eabi

      - name: Build Project
        working-directory: ${{github.workspace}}/pico-pulse
        shell: bash
        run: |
          echo ${{ github.ref }}
          mkdir build
          cd build
          cmake .. -DPICO_SDK_PATH=../../pico-sdk -DCMAKE_BUILD_TYPE=Release -DPICO_BOARD=pico2_w
          cmake --build .
          cd ..
          ls -lrt build/*.uf2
